export interface typeOfMenuReducer {
    A: number,
    B: number,
    C: number,
    R: number,
    O: number,
    G: number,
    GSlope: string,
    AModel: string,
    BModel: string,
    CModel: string,
    floor: string,
    unit: string,
    animate: boolean,
    lineArea: string,
    materialColor: boolean,
}